# -*- coding: utf-8 -*-
"""vuong598hw1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y7f0-R-FpwXb7kST7jpfcqMHZhhWC2h1
"""

# Bryan Vuong
# MAE 598 HW1

import numpy as np
from scipy.optimize import minimize

# Equation and Definitions
def f(x):
  #variables
    x1 = x[0]
    x2 = x[1]
    x3 = x[2]
    x4 = x[3]
    x5 = x[4]
    return (x1 - x2)**2 + (x2 + x3 -2)**2 + (x4-1)**2 + (x5-1)**2

def constraints1(x): 
    return x[0] + (3*x[2])

def constraints2(x):
    return x[2] + x[3] - (2*x[4])

def constraints3(x):
    return x[1] - x[4]

# initial guess
x0 = [-2,1,3,5,-1]


# bounds
bnds = ((-10,10),(-10,10),(-10,10),(-10,10),(-10,10))

# constraints
cons = ({'type': 'eq', 'fun': constraints1},
        {'type': 'eq', 'fun': constraints2},
        {'type': 'eq', 'fun': constraints3})

# answers
ans = minimize(f,x0,method='SLSQP',bounds=bnds,constraints=cons)
x = ans.x

print('Solution')
print('x1 = ' + str(x[0]))
print('x2 = ' + str(x[1]))
print('x3 = ' + str(x[2]))
print('x4 = ' + str(x[3]))
print('x5 = ' + str(x[4]))